# use new container-based travis workers
sudo: false
dist: trusty

language: python

cache:
  directories:
  - /home/travis/download
  - /home/travis/miniconda
  - /home/travis/.cache/pip

env:
  matrix:
    # test theano keras backend (theano first, because it's slower)
    - KERAS_BACKEND="theano" COVERAGE="true"
    # test tensorflow keras backend
    - KERAS_BACKEND="tensorflow" COVERAGE="true"
    # pylint checks skip the tests
    - RUN_PYLINT="true" SKIP_TESTS="true"

notifications:
  email: false

install: source build_tools/travis/install.sh
script: bash build_tools/travis/test_script.sh
after_success: source build_tools/travis/after_success.sh
